### ISSUE TITLE
Does it works?

### ISSUE THREAD

**Issue by HaolyShiit** [Flaick/LR-License-Plate-Generation#1]
Hello, thans for your work!
I build similar model for generating LR images(color images as input ),  but the loss keeps nearly unchanged, and the result is very bad.
Can you give some advice？

**Comment by Flaick** [comment]
I guess the weight for the GAN loss will influence the result. I remember that I firstly train the generator for a while and then add the GAN loss on it, because the discriminator is usually better than the generator at the first time.

**Comment by HaolyShiit** [comment]
> I guess the weight for the GAN loss will influence the result. I remember that I firstly train the generator for a while and then add the GAN loss on it, because the discriminator is usually better than the generator at the first time.

Thank you!
